### ISSUE TITLE
NotImplementedException with IsExpression

### ISSUE THREAD

**Issue by Krizzzn** [NRules/NRules#113]
With the following setup I can trigger a not implemented exception

```
When()
.Not<SomeFact>(m => m.SubFact is object)
```

As long as I have only one rule that does this everything is okay. Once I add a second, I'll get a NotImplementedException. 

```
Result Message:	
Failed to compile rule
Rules.Pricing.xxxxxx
($var1$.SubFact Is Object)
```

From looking at the source I think the ExpressionComparer is throwing the error.
Am I doing something stupid, or is this a valid bug?

BTW: I was able to get a similiar behavior with 

```
When()
Not<SomeFact>(m => (m.SubFact as Something).Value )
```

**Comment by Krizzzn** [comment]
If you accept this PR, would you prefer that I open it for the main-0.5 branch? 
(I would love to see that change in a 0.5.3)

**Comment by snikolayev** [comment]
Hi @Krizzzn 
Thank you for finding and fixing this issue! It's indeed a defect with the expression comparer. 
So that you understand what's going on, when you have one rule with a particular expression, it's directly compiled to the rete network. When you have two or more rules using the same exact expression, the rule compiler is starting to look for opportunities to share nodes in the rete graph, at which point it needs to compare expressions. This particular expression comparison was not implemented, hence the exception.

I'll review the PR. Once accepted, I agree it's worth patching in 0.5.x. I'll merge it to the maint-0.5 branch.

**Comment by Krizzzn** [comment]
Great. Thank you for merging and the explanation.
