### ISSUE TITLE
.Compile Method does not exist.

### ISSUE THREAD

**Issue by MPNaresh** [NRules/NRules#134]
I am referring to this page and followed the steps

https://github.com/NRules/NRules/wiki/Getting-Started

I am getting this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'RuleRepository' does not contain a definition for 'Compile' and no extension method 'Compile' accepting a first argument of type 'RuleRepository' could be found (are you missing a using directive or an assembly reference?)

**Comment by MPNaresh** [comment]
Found it. We need to use namespace NRules

**Comment by mbarqawi** [comment]
I have the Same, How to fix this ?

**Comment by MPNaresh** [comment]
I think you only need to include a namespace. I don't remember by heart. If
you sownload their code, you will know the namespace name for sure, because
thats how I resolved for myself by comparing my code with their example.
The problem was "compile" method definition exists in a different namespace
of same class.

**Comment by snikolayev** [comment]
Make sure to install the nuget package https://www.nuget.org/packages/NRules (this will add references to three libraries to your project - `NRules`, `NRules.RuleModel` and `NRules.Fluent`; it is the `NRules` library that has the definition of the `Compile` extension method).
Then try adding the following using statement:
```c#
using NRules;
```
Alternatively, instead of:
```c#
var factory = repository.Compile();
```
You can use the following. It is more verbose, but does not use extension methods.
```c#
var compiler = new RuleCompiler();
var factory = compiler.Compile(repository.GetRules());
```
