### ISSUE TITLE
How to properly add / update information and re-evaluate rules

### ISSUE THREAD

**Issue by mariotoffia** [NRules/NRules#135]
Hi, I'm completely new to NRules and I've tried out MissManners project. I wonder how to properly e.g. add guest facts to the memory and make the rules engine (effectively) re-evaluate the rules around (in this case seating :). I've added a ```Reset()``` method on the ```Counter``` and made ```SeatId``` in the ```LastSeat``` types. and added the following after the orginal ```session.Fire()``` method.

Why I'm wondering? I'm going to need frequent re-evaluation of my rules by incoming events from remote websocket / REST enpoints thus trigger rule(s) now an then. Since it is rather high load I need to re-/evaluate rules rather quickly in order for it to scale properly. Currently I'm doing this in plan code but it getting harder and harder to maintain.

Cheers,
 Mario

```csharp
      Console.WriteLine("Hit ENTER to to insert new Male I1.H17, Female I2, H17");
      Console.ReadLine();
      session.Insert(new Guest("I1", Gender.Male, new Hobby("H17")));
      session.Insert(new Guest("I2", Gender.Female, new Hobby("H17")));

      lastSeat.SeatId = 7;
      session.Update(lastSeat);

      session.RetractAll(session.Query<Seating>().ToArray());
      session.RetractAll(session.Query<Path>());
      session.RetractAll(session.Query<Chosen>());

      count.Reset();
      session.Update(count);

      context.SetState(ContextState.StartUp);
      session.Update(context);
      session.Fire(); // Need to do this otherwise only AssignFirstSeat rule gets triggered.
```

**Comment by snikolayev** [comment]
Hi @mariotoffia. In general, rules are (re)evaluated whenever you call `Insert`/`Update`/`Retract` on the session with the relevant facts. Then you call `Fire` method, so that the rules that got activated actually execute. After that you may tell the engine that it needs to re-evaluate rules again, by updating more facts in the session (obviously, not all rules are necessarily re-evaluated, since Rete algorithm is efficient, and only evaluates those rules that are affected by the updated facts). Then you call `Fire` again, and any newly activated rules (or any re-activated rules) are executed. And so on. This is what's called a Match/Resolve/Act cycle in the domain of rules engines.
Regarding Miss Manners example. It's probably not the best example to illustrate re-evaluation, This algorithm is stateful, and once all rules have fired, it reaches the solution and the rules won't fire again. This is because during the calculation it updates the facts, and adds new ones, in such a way that the rules no longer match. So, for it to start again, you need to reset the facts back to the original state by updating/retracting them (which is what you did). I would look at other samples instead. For example SimpleRules sample would be a much better place to start.
So, it very much depends on the specific rules and facts. All you need for the rules engine to re-evaluate is to tell it what changed. Whether that translates to rules firing is entirely dependent on whether all rule conditions are satisfied or not (mostly, but it will suffice for this explanation). If all conditions are satisfied, the rule is activated, and its actions will run once you call `Fire`.
If you have a more specific example that is closer to what you are actually trying to do, I may be able to tailor my answer to your particular case.

**Comment by mariotoffia** [comment]
@snikolayev Thanks for the answer and explanation!

So if I understand you right, each time a one of my _analytics_ instances returns a new value (and put that into a fact instance) I need to invoke ```Fire``` to make sure that the rules connected to that fact will fire.

What I've done is a simple Stocktrading _"Robot"_ that uses a set of _Algorithms_ that in certain combinations and certain values (calculated from the _Algorithms_) e.g. a MACD (Moving Averages Convergence Divergense) with a RSI (Relative Strength Index) to determine when It might be a good time buy or sell stocks (it is much more complicated than that :). But Let's assume that I only use MACD and RSI.

For each stock, within different time frames (such as 1min, 3min, 15 min, 30 min, 1hr, 1day, 1week) it do have one instance of each algorithm, i.e. no of algorithms = [number of timeframes] * [number of stocks] * 2 (since RSI and MACD) * [number of exchanges].

Each Algorithm gets fed data in those by data polled (or pushed) from the exchanges. Each time I put in value a calculated e.g. RSI or MACD values gets produced. Then I need to do decisions on those if it is a good time to buy a stock or sell it (that itself is a complex rules system).

So, if I understand you correctly each time i update a fact I need to ```Fire``` the rule mechanism and in my case this could be done hundreds of times per second since data is literally poring in.

If so, is it thread safe or should I have a separated out the rules into several worker threads (today I use TPL) and use e.g. a producer / consumer pattern to feed the data and do ```Fire``` on those.

Do you see any performance issues?
Can I make everything _"stateless"_ and thus it just react on the input of data and thus increase performance?

How do I properly construct such rules memory that gets updated hundreds times of a second and may fire one or more rule. Should I partition the rules domain since some parts is more trickier than others. Such as selling or buying is a process where several indicators, orderbook and time (and weakness / strength of the market is for current stock) and thus there are many descision while actually purchasing a stock (or selling). Thus a buy period may stretch over say 1 minute - 1hour or so (sometimes, while accumulating days or even weeks).

Cheers,
 Mario

**Comment by snikolayev** [comment]
Hi @mariotoffia, I cannot comment on the algorithmic or trading aspects of your question, but I can answer NRules related portions.
You don't need to call `Fire` after every fact update, but you have to call `Fire` in order to run the rules that got activated due to fact updates. The way this would normally look is that there is a set of facts that need to be updated (or inserted/retracted), so you do that for all those facts, and then you call `Fire` once. And you do that as frequently as needed - if no rules are active then `Fire` is just a no op.
A session in NRules is single threaded, so you will have to manage access to it in some way. There are few things to consider. First, you are saying that facts are pouring in - for high velocity data like that you probably need to throttle/conflate it; NRules will not do it for you. Second, it sounds like the facts in your system can easily be partitioned into orthogonal sets, where decisions on one set don't depend on other sets. If so, you can create multiple sessions - one per such set, and run partitions in parallel (or even scale out to multiple nodes). Third, if the logic itself is independent for different types of decisions, you can obviously partition the logic too, and just compile different subsets of rules into different session factories. Fourth, if you just keep adding facts into a session, eventually you'll hit performance issues and bust memory. So, you need to retract the facts you no longer need. For historical analytics I suggest aggregating granular facts into some metric where you then retract individual facts and just keep the metric.
You can't really be stateless, since the rules engine and Rete algorithm are by definition stateful. You are responsible for either retracting facts you no longer need, or synthesizing them into aggregate metrics that you keep for extended periods of time.

**Comment by mariotoffia** [comment]
@snikolayev Thanks again for your explanations and help!

I will prototype parts of my most cumbersome code to NRules and see how it will perform.

Tanks again for your kind support!

Cheers,
 Mario

**Comment by snikolayev** [comment]
Great! let me know if I can help more. I'm going to close this issue. if you just want to chat or ask questions, gitter might be a good place.

**Comment by alan-yeung** [comment]
I have a question about how update works.
In my example, I have 3 rule definitions with different priorities in the same rule set:
- Rule A, priority 10, condition: isUpdated == false, action: isUpdated = true (will match)
- Rule B, priority 9, condition: true, action: update (dummy rule just to update fact after rule A)
- Rule C, priority 8, condition: isUpdated == true, action: doSomething (will match only after fact is updated)
How many times will rule C get evaluated - once (with updated fact) or twice (with original fact and updated fact)?

**Comment by snikolayev** [comment]
@alan-yeung The engine can only possibly re-evaluate conditions if you tell it that something changed. Since you are only calling the update once (in rule B), the condition will only evaluate once, when you call update.
When you are saying "evaluated" I assume you are talking about evaluating rule conditions, not executing (aka firing) actions.
The best way to understand this is probably just writing a quick test and checking what happens.

On a side note, please ask questions on the forum, user group or stack overflow. Try to only use issues for bug reports and feature requests.
