### ISSUE TITLE
NRules comparing with WF Rules

### ISSUE THREAD

**Issue by projektsdb** [NRules/NRules#136]
This is more a question. We are looking for business rules engine (for .NET). We see WF Rules and NRules as options. As we are just in the beginning of our journey, could you please help us to understand how these are different and why NRules could be better?

P.S. Btw, in the future we would have to create rules editor by ourselves. Thus we would not use Fluent Api. The idea is that Rules editor would create rules and save them in database or somewhere. Rules would be saved in some serialized way for easier use for BRE. Those searialized Rules would be afterwards sent to BRE for execution.

**Comment by snikolayev** [comment]
@projektsdb I don't have a lot of experience with WF, but here is my understanding.
WF has ability to express state machines and sequential workflows. State machine speaks for itself, and sequential workflow executes activities in order with conditional branching. In WF3 you can have a PolicyActivity that implements a rudimentary forward chaining rules engine with a rules designer that can be used to externalize simple rules. It does not seem to support joins, aggregates and is very vanilla. In WF4 and 4.5 it's altogether deprecated. You can still wrap WF3 policy in WF4, but it looks more like a migration strategy for old stuff, rather than a well supported feature.
NRules is a fully featured inference engine under active development. The main difference from other rules engines is that it's "code first" and the only currently supported DSL is in C#.
There are plans to add other types of DSL in the future, including an external rules language and a rules editor. But that's not going to happen overnight.
Does this answer your question?
