### ISSUE TITLE
Restrictive Event Arguments

### ISSUE THREAD

**Issue by ThaBaer** [NRules/NRules#139]
Hi,
I've some code that acts on events for facts being inserted and retracted (IEventProvider).
Now I wanted to write tests for that, but failed because I can't instantiate or mock the EventArguments to raise the events.
Is the restrictive implementation of e.g. WorkingMemoryEventArgs intentional? Is there a way to raise those without instantiating a whole session? What am I missing?
Thanks.

Ps: Great lib, love it!

**Comment by snikolayev** [comment]
Hi @ThaBaer 
I'll have to think about what to do here. The reason it is restricted is because the events are created using internal structures of the engine, so constructors have to also be internal. If I convert internal objects to public every time I raise an event, it will incur an unacceptable performance penalty. 
Meanwhile, your best workaround is probably to have a layer between the event listeners and actual logic,  where you would deconstruct event args  into mockable objects. Then you should be able to unit test the logic.

**Comment by snikolayev** [comment]
I looked at it, and I can make the constructors public without sacrificing performance.

**Comment by ThaBaer** [comment]
Great, thanks.

Awesome lib, btw.
