### ISSUE TITLE
DSL Extensions

### ISSUE THREAD

**Issue by ThaBaer** [NRules/NRules#144]
Hi,

I have an issue with DSL extensions I don't really understand.

This works:
`public static ILeftHandSideExpression NotEmpty<TEnum>(this ILeftHandSideExpression lhs, IEnumerable<TEnum> enumerable) where TEnum : ISomeInterface`
`{`
`return lhs.Having(() => enumerable.Count() > 0);`
`}`

If you omit the where-clause a NullReferenceException is thrown at rule building.

Regards.

**Comment by snikolayev** [comment]
@ThaBaer can you please include an example of a rule that uses this extension, that fails to build?

**Comment by snikolayev** [comment]
@ThaBaer it would still be helpful to see a rule example where this extension is used, but by inferring from the extension, I'm assuming you are passing some previously matched fact into this method as `enumerable` parameter.
The thing is, this will not work, whether you have `where` clause or not. You cannot treat binding variables as actual variables and pass them around (or manipulate in any way outside of rule expressions). This is also described in the [wiki](https://github.com/NRules/NRules/wiki/Fluent-Rules-DSL). Binding variables are used as symbols or tokens, so that rule builder can replace them with expression parameters. The actual variables always remain null (or default value for value types). So, in this case you probably passed it into this method, and since it's always null, `enumerable.Count()` caused NullReferenceException. If you give a rule example, it will be easier for me to explain what actually happened.

**Comment by ThaBaer** [comment]
@snikolayev  While trying to build a minimal example, I think I've found the cause and it's basically what you stated.
The where-clause version uses a specific paramter name, that is the same as the one in the rule. Therefore the binding works.
The generic one without the where-clause uses a different, generic parameter name, thus the binding fails.

I've read the wiki and technically this is within the expression (it does work outside of the extension method). It's just that the different method signature breaks the token naming.

I wonder if there's a way around this, because it really limits the use cases for DSL extensions.

**Comment by snikolayev** [comment]
The idea behind DSL extensions was to provide ability to name match methods in a more domain-friendly way. You can use them to extend the DSL further, like what you are trying to do, but that comes at a price, because you may need to manipulate expression trees within extension methods.
Taking your example, for instance; instead of passing `IEnumerable<T>` you can pass `Expression<Func<IEnumerable<T>>>`, and pass the binding variable there as `() => myVariable`. Now, being an expression, you can compose it with other expressions and pass that to the `Having` method. Obviously composing expression trees in code is difficult, but that's the workaround if you truly want to push the boundary of reusable DSL extensions.

For example, here is your NotEmpty extension:
```c#
public static class MyExtensions
{
    public static ILeftHandSideExpression NotEmpty<T>(this ILeftHandSideExpression lhs, Expression<Func<IEnumerable<T>>> enumerable)
    {
        //Binding variable
        var alias = enumerable.Body;
            
        //Count method
        var genericCountMethod = typeof(Enumerable).GetMethods()
            .Single(x => x.Name == nameof(Enumerable.Count) && x.IsStatic && x.GetParameters().Length == 1);
        var countMethod = genericCountMethod.MakeGenericMethod(typeof(T));
            
        //Condition
        var condition = Expression.Lambda<Func<bool>>(
            Expression.GreaterThan(
                Expression.Call(null, countMethod, alias),
                Expression.Constant(0)));

        return lhs.Having(condition);
    }
}
```

This stuff only evaluates once when compiling the rules, and is then compiled to a delegate that's used at run time.

**Comment by ThaBaer** [comment]
@snikolayev 
Great support, thanks!
Much appreciated.

I'll try to build some using this approach, but I guess due to the complexity it seldom warrants the cost.
