### ISSUE TITLE
Fail on direct update/retract of linked facts

### ISSUE THREAD

**Issue by victormp1988** [NRules/NRules#149]
Hello,

I have noticed that if you call TryRetractAll() method passing a set of facts with a LinkedFact within that set, workingMemory object throws an ArgumentException. 
First of all, it removes the root facts, so the linked fact is removed automatically from the session, however TryRetract method is still looping throught toPropagateVariable which still contains the linked fact, so it calls _workingMemory.RemoveFact() method passing the linked fact.
I know that the obvious solution is to avoid pass linked facts to that method, however I guess it should handle this case.

![image](https://user-images.githubusercontent.com/22835198/37980426-67319d54-31eb-11e8-8e75-1706e4c2750f.png)

**Comment by snikolayev** [comment]
Hi Victor,
It's not correct to directly update or retract linked facts via the session, because that will break the machinery of the linked facts - there is additional bookkeeping information about linked facts that would become corrupted. Linked facts must be managed via the corresponding rule match (via context or declaratively using the `yield` statement).
I think an appropriate change here is to fail fast and prevent updates or retracts of linked facts.

**Comment by victormp1988** [comment]
Hi Sergiy,

I understand... It makes sense. Just one question... How can I identify
which facts are linked facts in a session. For example I would like to grab
all linked facts created in a session after a Fire() command.

Thanks for your answer.

2018-04-01 23:04 GMT+02:00 Sergiy Nikolayev <notifications@github.com>:

**Comment by snikolayev** [comment]
If you are pulling facts using session.Query method, you'd need to somehow demarcate those facts yourself. I.e. implement some interface, or tag them with a custom attribute. 
If you are handling newly inserted facts using IEventProvider.FactInserted event, you are getting IFact as a property on EventArgs passed to your event handler. IFact has a Source property, which can tell you that the fact is linked.

**Comment by victormp1988** [comment]
Great, I will play around with these options.

Thank you again.

2018-04-04 6:50 GMT+02:00 Sergiy Nikolayev <notifications@github.com>:
