### ISSUE TITLE
Rule engine as a service

### ISSUE THREAD

**Issue by patolax** [NRules/NRules#151]
Hi,

Just want to know, how to package everything into a web api/service. 

How do I retain working memory and apply new facts as they come in through the api (create a singleton session and reuse it, or create a new session and reload all data and then evaluate?)
How do we save the memory or state so that service can reload everything after a shutdown and startup.

**Comment by snikolayev** [comment]
Hello, similar questions were asked on the gitter forum and on the user group, so I'm just going paste a representative answer here. LMK if this answers your question, or if you have further questions.
In general, it's better to ask questions on the forum, user group or stack overflow, and use issues for bug reports and feature requests.

If the engine is hosted in a service, where multiple clients can call, there are several options how to go about it. In all cases you compile the rules into a session factory only once per service instance. The differences arise in a way you manage sessions. 1) Stateless service where you create a new session on each request, load it with facts and run the rules - this works well when the number of facts is small (i.e. validating a handful of domain objects. 2) Maintain affinity between clients and services, so that you keep the session for a given client around. This basically makes your services stateful, and only works if you have a few clients. 3) Not currently supported by NRules, but I imagine this can be added if there is interest - be able to persist and restore a session (say in a document database), so that when a client request comes in, you restore the session, add new facts, run the rules and save the session back. As I said, this is currently not supported, and currently this means option 1. 3) Maintain a pool of interchangeable sessions, where a bulk of facts is the same (say, reference data) and the facts specific to the client request are a few that you add, run rules, and then retract when done (and put the session back to the pool). 4) Write rules in such a way that one session can handle facts from multiple clients (i.e join by client ID); so that you can run inference for multiple clients at the same time (since session is single-threaded, need to synchronize clients around session access).

**Comment by patolax** [comment]
thanks for the reply. 

If I use the same session object and call update sub set of facts and then fire each time, I noticed that working memory is not updating based on updates I do when a rule is fires. If I do update-fire multiple times on same session object, outcomes are wrong due to working memory issues. Is this a wrong approach? Do I have to create session object and insert facts every time, in order to get the correct outcome?

**Comment by snikolayev** [comment]
Updating existing facts in the existing session is perfectly valid. Updating facts in the session updates them in the working memory. Calling "fire" again would re-fire the rules that match the updated facts. What "wrong" outcomes are you observing? It would be helpful if you explained what you expect to happen vs, what you see is happening. Even better is a failing unit test that asserts expected behavior.

**Comment by patolax** [comment]
I ll try to get a unit test for you. But I think i am struggling with conceptual thing. Here is a simple rule.
AssignNewZone method which is called in Do(), updates the facts as rule fires. Do you take these changes into account in the working memory and refire rules? or do I have to explicitly call session.update() on these changed objects as well?

    public class MachineEnterRule : Rule
    {
        public override void Define()
        {
            Asset asset = null;
            Asset machine = null;
            Event eventData = null;

            When()
                .Match<Event>(() => eventData, e => e.Type == EventType.Enter)
                .Match<Asset>(() => asset, a => a.Id == eventData.AssetId, a => a.Location == "Machine", a => a.CurrentZone == ZoneType.Storage)
                .Match<Asset>(() => machine, a => a.Id == "Machine", a => a.Status == AssetStatus.Empty);


            Then()
                .Do(ctx => AssignNewZone(asset, machine));
        }

        private void AssignNewZone(Asset asset, Asset machine)
        {
            Console.WriteLine($"Fire MachineEnterRule {asset.Name} => {asset.CurrentZone.ToString()} to {ZoneType.CX.ToString()} => Notify Service");
            asset.CurrentZone = ZoneType.Port;
            machine.Status = AssetStatus.Full;
            
        }
    }

**Comment by snikolayev** [comment]
You almost got there - you do need to tell the rules engine what you updated. But you can do it via IContext right there in the action. Use `ctx.Update()` on both `asset` and `machine`.
Be careful not to re-fire the same rule again. You implemented it correctly, and you have a guard clause in the rule conditions `a.Status == Empty`, which will de-activate this rule as soon as you set the `machine.Status` in the action.

**Comment by patolax** [comment]
thanks.
