### ISSUE TITLE
Linked facts not retracted+ after retracting facts, after session has finished firing

### ISSUE THREAD

**Issue by ben-jacobs** [NRules/NRules#163]
Hi,

I may have messed something up, but I think I've encountered a strange scenario where linked facts are not retracted from the session when the "owing" facts are retracted after the session has completed firing.

i.e. session.RetractAll(session.Query<object>());

I'm doing this because I'm trying to avoid creating a new session and repopulating it with common facts 
(i.e. I'm not really retracting object, I'm being a bit more specific)

Is there a specific way to remove these linked facts, or should I just create a new session?

Cheers,

Ben

**Comment by snikolayev** [comment]
@ben-jacobs this is not a good way to clear the session. Practically, in your case RetractAll probably just throws an exception, which is why it seems to you that the facts remain in the session. When you do session.Query, it also returns the linked facts, which cannot be directly retracted, so RetractAll fails (you can wrap it in try/catch and confirm if that's true).
If you really just need an empty session, you are better off just creating a new one, as you yourself suggested. Creating a new session is extremely fast (way-way faster than trying to remove facts from the old session).

**Comment by snikolayev** [comment]
@ben-jacobs I'm closing this, please reopen if you think there is still an issue here.
