### ISSUE TITLE
Sorted Aggregator

### ISSUE THREAD

**Issue by a046** [NRules/NRules#171]
**Idea/Motivation:**
I want a "Sorted" aggregator to allow me to efficiently select the first fact OR first few facts from an aggregation of matched facts. This will be used for cases where many facts are matched, but the action only has to use one (or a few) of the facts to achieve the desired outcome but must consider them according to certain sorting criteria.

Using the Collect aggregator and sorting the aggregation inside the action obviously performs very poorly as did some other approaches I tried.

Instead, a "reactive LINQ query" is ideal as the aggregation can be sorted as new facts are added or an existing fact is modified.

I also believe the current list of operators supported by reactive LINQ queries is sorely missing an "OrderBy" or "Sort"!

**Implementation Thoughts / Rough Design:**
Having a SortedAggregator is convenient as it could be used in place of .Collect OR chained with Project/Select or Flatten/SelectMany.

I have created a "CustomAggregator" as a prototype and found having a IComparer<TElement> and SortedDictionary<TElement, IFact> on the aggregator works well to implement the feature in a performant manner.

To allow for future optimisations of the sorting logic (e.g. multi-key sorting in a lazy/deferred manner), I think it's ideal to keep an array of individual comparers on the Aggregator and simply chain them together when creating the SortedDictionary rather than having a single comparer. Thoughts? 

One way of implementing that is shoehorning it into existing code (ExpressionMap/LambdaExpressions) by using Comparison<T> expressions for comparers and giving each comparer a unique name in the dictionary which will ensure it remains ordered (e.g. Comparer01, Comparer02 etc. if there are > 10 comparers).

Alternatively, adding a new collection of IComparers (or Comparison<T>s) onto AggregateBuilder + AggregateElement + implementing expression rewriting (if needed?) for this. Any other ideas?

I mostly want to use canonical model and would ideally just want to implement it in that initially, but have considered a design for NRules.Fluent which is similar to LINQ. Do contributions to the canonical model generally come with the expectation that NRules.Fluent support is implemented to?

Possible design for NRules.Fluent:
1. Add new subclass of IQuery, IOrderedQuery: Has two new methods "ThenBy" and "ThenByDescending"
2. Add new methods (QueryExtensions) onto IQuery which returns IOrderedQuery: OrderBy, OrderByDescending
3. Add the four methods above onto QueryExpression.cs
4. Create an "OrderBy" object with a key selector expression + Asc/Desc flag
5. Add a stack of "OrderBy"'s onto QueryExpression
6. ThenBy/ThenByDescending push an "OrderBy" onto the stack
7. OrderBy/OrderByDescending creates the aggregator and passes in all of the "OrderBys" (comparers), clearing the stack of OrderBys in the process.

**Comment by snikolayev** [comment]
First of all, thank you for such a detailed proposal/design write-up! It sounds like a useful capability to add, so I'm fine moving forward with it.
It should be easy to start by adding a single-key sorting capability with OrderBy and OrderByDescending, which would fit nicely into the existing framework (and should cover like 90% of the cases). And then separately can extend into multi-key sorting with ThenBy and ThenByDescending, like you described. I was thinking to change the aggregator expression map from a dictionary into an ordered list of named expressions, at which point it should be easy to add multiple expressions with the same name, for different sorting keys; no need to shoehorn anything. This should also nicely extend into multi-key grouping at some point in the future.
It sounds like you already have it implemented for the single-key case using a custom aggregator. If so, it's just a small code refactoring to turn that custom aggregator into a built-in one. Would you be game contributing it?

**Comment by a046** [comment]
My initial plan was to have canonical use just use comparers and fluent also offer key selectors, but maybe it's nicer using key selectors throughout and adding comparers later if the need arises? What were you thinking?

The issue with a selector rather than comparer is I'd need a way to know whether it was ascending or descending, using separate aggregators isn't nice and wouldnt work for multi keys. Simple solution is having another expression in the map for direction, and it also scales to multi keys.

I think starting with a single key is a good idea, i strongly believe any subsequent sorts should be done in the same aggregator node but the design for ThenBy is still feasible after starting with a single key selector.

Interesting, modifying ExpressionMap to allow duplicates would make multi key sorting fit simply. Would it be worthwhile using a Dictionary<string, list> or would the performance regression of the lookup be negligible?

My implementation of a custom aggregator used an IComparer, so it's got some ugly hacks. I'd have to refactor it a little, retrofit tests, possibly add fluent support and so on. Ill do it, but it won't happen over night!

**Comment by snikolayev** [comment]
Yes, I was thinking to use key selector first (consistent with IEnumerable.OrderBy), and add support for comparers later as a separate thing (similar to [this](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netframework-4.7.2#System_Linq_Enumerable_OrderBy__2_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Collections_Generic_IComparer___1__)), and also do it not just for OrderBy, but also support IEqualityComparer for GroupBy (like [this](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby?view=netframework-4.7.2#System_Linq_Enumerable_GroupBy__3_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Func___0___2__System_Collections_Generic_IEqualityComparer___1__)).
As far as ascending/descending, I was thinking that expression map would contain KeySelectorAscending or KeySelectorDescending.
Later, when adding support for multi-key sorting, we can change expression map to an ordered collection, as previously discussed, and have as many KeySelectorAscending and KeySelectorDescending expressions as needed. I agree that when adding multi-key sorting (or grouping to that end), they should compile to a single aggregator for performance reasons. I can also totally envision different implementations for a single key sorting aggregator vs a multi-key one, since 90% of the cases will be single-key anyway, and you want that to be as performant as possible.
I don't think there are any performance concerns with changing the expression map from a dictionary to the ordered collection. It's only used at rules compile time. At rules run time it will all get compiled to an appropriate aggregator, which obviously should be implemented as efficiently as possible.
If you want to implement it and get over the finish line that's obviously greatly appreciated. However, if you don't feel like spending too much time on this, you can just push the custom aggregator that you have as is on a feature branch; this will then give me a head start.
In either case - thank you for showing interest and engaging on this issue!

**Comment by linanqiu** [comment]
This also fits in well with a `ToDictionary` feature that I want to add, especially if we go down the route of single key.

e.g.

```csharp
.Query(() => c, q => q
    .Match<T>()
    .OrderBy(t => t.Key) // returns an IOrderedQuery (whether it's <TKey, T> or just <T> up to you. I'd prefer the former) that can be implemented either linearly or tree
    .First()
```

or

```csharp

Query(() => c, q => q
    .Match<T>()
    .ToDictionary(t => t.Key) // returns an IKeyedQuery<TKey, T> that implements IDictionary<TKey, T>
    .Select(d =>d["RandomKey"])
```

**Comment by snikolayev** [comment]
@linanqiu can you please put that in a separate issue, so that we don't mix threads? I want to discuss how that ToDictionary would look like

**Comment by linanqiu** [comment]
Makes sense. Will do that.

**Comment by a046** [comment]
I've run into a minor problem, my SortedDictionary approach only really worked as my key was a whole Fact object and I could pass in Comparator< TFact> and not add duplicates to the SortedDictionary. 

None of the .Net data structures seem very suited for this. A binary search tree would work well, but the issue is that after a fact is updated you would no longer be able to calculate the old key anyway -- more elegant data structures have the same issue.

I'm thinking the best approach may be to have a SortedDictionary<TKey, List< TFact>> AND a Dictionary<TFact, TKey> for looking up the "current" key. Thoughts?

**Comment by snikolayev** [comment]
I think having a composite collection is good (I'm a bit hesitant about the List, but should be Ok, if number of key collisions is small). 
I reviewed the PR and added a bunch of comments.
The main comment is about whether at the DSL level OrderBy should be it's own clause, or if it should be a modifier to the Collect clause. The later seems to be more natural to me, but we should discuss in PR comments.

**Comment by a046** [comment]
> I think having a composite collection is good (I'm a bit hesitant about the List, but should be Ok, if number of key collisions is small).
> I reviewed the PR and added a bunch of comments.
> The main comment is about whether at the DSL level OrderBy should be it's own clause, or if it should be a modifier to the Collect clause. The later seems to be more natural to me, but we should discuss in PR comments.

Thanks, I'll have a look! I can't see any comments on the PR at the moment however?

**Comment by snikolayev** [comment]
I needed to hit Submit on the review, duh. You should see them now

**Comment by a046** [comment]
Pending the open discussion on my last PR, I'm also planning to get started on the remaining parts now, want to do it in a few steps:
1. Refactor ExpressionMap to allow duplicates.
2. Add a MultiKeySortedAggregator which just uses the existing SortedFactCollection with a chained comparer. This will also include Fluent DSL as explained above.
3. Refactor the MultiKeySortedAggregator to use a more efficient and multi-key aware approach.

Any concerns with that approach? I think it'd be great to have all the changes to the public interface (up to 2) in 0.9.0.

**Comment by snikolayev** [comment]
Makes sense, and agree on including this in 0.9.0. The only thing is that I would first finish the swing on stacking of DSL extensions with the single-key OrderBy, so that we have that implementation committed to develop, and only then move to the multi-key sort.
One additional thing - I just merged my feature branch to develop, which introduces some changes into how the canonical model is built. I added a layer of static factory methods (defined in the Builders/Element class), that provide similar functionality to static factory methods on Expression class to build expression trees. These factory methods simplify building of rule definitions a lot.
The builders are still there, but they are just a thin layer on top of the static factory methods.
And validations are now located in the ElementValidator class.
Just a heads up.

**Comment by a046** [comment]
For the multi key aggregator I plan to initially implement it in a naive way with a nested/compound comparer and an array of keys as the key. I'll give implementing this a go after the current PR is complete if there's no objections,

But after that, thinking about the multi-key aggregator and improving the performance of SortedFactCollection/SortedAggregor:

**Improving SortedFactCollection**
Instead of a SortedDictionary<TKey, List<IFact>> + Dictionary<IFact, TKey>, I think it would be better to re-use the NRules.Collections.PriorityQueue and add support for removing elements and iteration.

To support iteration: Add enumerator for PriorityQueue, either clone internals or rebuild PriorityQueue as in Sedgewick's Java implementation: https://algs4.cs.princeton.edu/24pq/MinPQ.java.html

To Support removing elements: Add Dequeue(priority, value) method, implementation as in: http://www.mathcs.emory.edu/~cheung/Courses/171/Syllabus/9-BinTree/heap-delete.html

**MultiKey Aggregator**
For the eventual multi-key data structure, I think nesting PriorityQueues might work well. 

To optimize for the .First() or shortcircuiting case, it could be worthwhile using an interim linkedlist or similar for the nested collections, but i'm not sure it's worth the complexity/effort.

**Comment by snikolayev** [comment]
@a046 I'm still trying to visualize how multi-key sorted collection should work. I think I understand the idea of a multi-key composite comparer with the array of keys. Something to think about - how to not pay the penalty for multi-key sort when you only have one.
Regarding PriorityQueue - I don't understand how that's going to be helpful in multi-key sorting. I need to think more about it.

Overall though, this is looking great so far, great work!

**Comment by a046** [comment]
I was considering that the MultiKey case might have it's own Aggregator as they could have different implementations (as discussed earlier). But with a nested approach it might not even be necessary. At least in the interim with an array of keys + multi key comparer, it will make more sense to use a separate aggregator however.

The priority queue won't help with multi key sorting, it just seems to be a better data structure than the current implementation of SortedFactCollection -- and if using a nested structure it makes sense optimise it first.

**Comment by snikolayev** [comment]
On the priority queue. I suppose the biggest point of creating a sorted aggregator is so that the aggregated facts can be iterated over in the sorted order. The priority queue is just a heap underneath, so you can retrieve the smallest/largest element from it in O(1), but you cannot iterate over it, it's just not a supported operation on this data structure. So, it defeats the purpose.
SortedDictionary on the other hand is either a BST or a red-black tree, and has O(log n) traversal complexity.

**Comment by a046** [comment]
The implementation in Sedgewick just clones the PriorityQueue and sequentially removes the smallest/largest element for traversal which should be O(n). I think even for a BST etc., the traversal (but not search) complexity should be at least O(n) too by definition?

Either way possibly it's not worth modifying the PriorityQueue, and maybe just replacing the List with a LinkedList and having the Fact->Key map also keep track of the LinkedListNode might be nicer?

**Comment by snikolayev** [comment]
You are right, the full cost of traversal must be at least O(n). MSDN said that GetEnumetator on SortedDictionary is O(log n), so that’s what I meant. Then iterating through elements once you got the iterator must have additional cost.
I would definitely prefer not to clone the collection in order to iterate over it, to avoid extra allocations.
Replacing List with LinkedList s probably a good idea. BTW, that’s what I’m doing in OrderedHashSet.

**Comment by a046** [comment]
It seems implementing multi-key support any other way might just be a trade-off depending on the size/data shape -- i'm not sure if it can obviously be improved now. Note that LINQ to objects does something similar but has some more overhead by chaining comparers together.

I think this might be complete now?

**Comment by snikolayev** [comment]
Yes, I agree. And great work on this! I'm closing this issue.
