### ISSUE TITLE
Keyed Lookup (Dictionary) Aggregator

### ISSUE THREAD

**Issue by linanqiu** [NRules/NRules#175]
Create an aggregator that supports the following:

```csharp
ILookup<TKey, TValue> l;
IEnumerable<TValue> e;

When()
    .Query(() => l, q => q
        .Match<TKey>()
        .ToLookup(t => t.Key)) // has optional value selector override just like ToLookup in LINQ
    .Let(() => e, () => l[someKey]);
```

This fits well with how programmers will expect `ILookup` to perform in LINQ.

Currently this can be implemented as

```csharp
When()
    .Query(() => l, q => q
        .Match<TKey>()
        .Collect()
        .Select(c => c.ToLookup(t => t.Key))
```

which is less performant because the `Select()` is not reactively updated and instead created newly each time.

I intend to implement this so that ToLookup produces `ILookupQuery<TKey, TValue>` (similar to the IOrderedQuery mentioned in issue #171

**Comment by snikolayev** [comment]
One idea I have is to stack extension methods, where subsequent methods may modify the preceding ones. Similar to how OrderBy().ThenBy() stacks. We could say that Collect() puts facts in a collection, which by default is just IEnumerable<T>, but can be modified by subsequent extension methods (and still compile to a single aggregation node in Rete).
```c#
When()
    .Query(() => l, q => q
        .Match<SomeFact>()
        .Collect()
        .ToLookup(t => t.Key))
```
This is also more consistent with the way LINQ works, since you would normally apply ToLookup to an IEnumerable.
