### ISSUE TITLE
Not all rules firing

### ISSUE THREAD

**Issue by JimBoyd** [NRules/NRules#178]
Question: If the repository has 2 rules, but only 1 of the rules is firing, what would be the best approach to discovering why only 1 is firing instead of 2 ?

**Comment by snikolayev** [comment]
You would need to determine which of the conditions on the rule that's not firing don't match. You would need to put breakpoints in the conditions to determine that. Since you cannot directly put breakpoints inside lambda expressions, the suggested approach is to temporarily extract the condition into a method on the rule class, and put the breakpoint there.

P.S. Generally, please ask questions on the discussion forum, gitter chat or SO, and reserve GitHub issues for defects or feature requests.

**Comment by snikolayev** [comment]
Starting with 0.9.0 there will be a way to subscribe to events that will be raised when conditions are getting evaluated.
```c#
Session.Events.LhsExpressionEvaluatedEvent += ...
```
It's already implemented in develop branch, so if you don't mind building from source, you can try it out.
