### ISSUE TITLE
Question: Comparing lists

### ISSUE THREAD

**Issue by nmocruz** [NRules/NRules#184]
Hi, I really new to this kind of tools, but I was wondering it could fit in some requirements for a projects.
My problem is like find tasks for employees, and employees for task. Employee have skills and tasks also can demand some skills.
Maybe is my lack of experience on this, I'm not getting a clear way to express a query where I test a employee against a list of tasks or a task against a list of employees, taking in a account that they should match every task skills.

**Comment by a046** [comment]
I think you would want to insert individual employees and tasks as facts rather than lists. 

You could then set up a pattern for both the employee and task types and join on the skills required. That would make sense if all skills are mandatory. Then you can fire on the join and assign the task. 

You might have to tweak it/consider how to avoid assigning everything to the same person. One possible approach is matching on a grouping of employees rather than a single employee and using the OrderBy aggregator to preference employees with the least tasks (first fit) or do two passes using two rules of different priorities - one to identify potential employees and another to evenly assign.

I think it should work well, but the problem may change entirely if you want to extend your solution to also consider scheduling as the problem becomes more of a combinatorial problem.

By the way, you may get more help on the Google group, gitter chat or stackoverflow. GitHub issues are usually used just for feature requests and bug reports.

**Comment by nmocruz** [comment]
I need to explain better the model.
class Skill {  int id; string name }
class Employee {   ICollection<Skill> canDoSkills;   }
class Task {   ICollection<Skill> mandatorySkills;   }

I was just confuse how to express a predicate to exclude the employee.
when employee miss a skill in the task it should warn, so maybe should include the skill as a fact, but as you said maybe I avoid introduce complexity in the system.

other thing is I would like query about how can do what, with parameters, like the day, the the precise employee or task ids, but may it can be done build another rule. Should I start a new session to do this queries?

Thanks for you well, you can close this, next time I gonna use the gitter chat or stackoverflow.

**Comment by a046** [comment]
You can still add the warnings etc., I think the issue you are running into is related to the way the collections are modeled. If you use links rather than collections and do the joins through NRules, you'll be able to use the Extistential and Non-Existential operator (see https://github.com/NRules/NRules/wiki/Fluent-Rules-DSL) to achieve some of the things you are trying to do.

You can still achieve most of what you want with a collection on the object, but I think it won't be very natural and might not perform as well as the RETE network won't be exploiting the nature of the data.

You should be able to achieve the other query too, but I think it's an entirely different use case and probably makes sense to have it's own session + separate rules - unless you have some way of reconciling the functionalities logically.

**Comment by nmocruz** [comment]
I got it now, I need to used relationships between tasks skills and employees skills to find the ones missing on the employee side. I need to add EmployeeSkill, and TaskSkill objects to archive this more easily.
You are right, I want to reuse rules and data, but the context is different and I should include facts that matter to a single session. I have 2 main some scenarios, one is find people or tasks, other more complex is to solve a schedule for alot of employee and tasks, but it doesn't mean they should share more than the state of the data and some common rules. Unless there's any indexation data that is build on each session,
