### ISSUE TITLE
How to use Expression.ArrayIndex ?

### ISSUE THREAD

**Issue by RockStar201** [NRules/NRules#196]
List<RuleEngineEntity> rules = new List<RuleEngineEntity>();
            rules.Add(new RuleEngineEntity { FieldName = "Age", Name = "CustomerCheck", Value = 25 });

            RuleEngineRequestModel ruleEngineRequestModel = new RuleEngineRequestModel { ruleList = rules, customerData = new List<Customer>() { new Customer { Name = "A", Age = 25 }, new Customer { Name = "B", Age = 26 } }.ToArray() };

            session.InsertAll(ruleEngineRequestModel.customerData);

// creating rule  starts

            var modelPattern = builder.LeftHandSide().Pattern(typeof(RuleEngineRequestModel), "CustomerCheck");
            var modelParameter = modelPattern.Declaration.ToParameterExpression();
            var customerData = Expression.Property(modelParameter, nameof(RuleEngineRequestModel.customerData));

            var index = Expression.Parameter(typeof(int), "index");

            var customerDataList = Expression.ArrayIndex(customerData, Expression.Constant(index));

            var binaryExpression = Expression.GreaterThan(Expression.PropertycustomerDataList "Age"), Expression.Constant(25));

**Comment by snikolayev** [comment]
I don't understand the question, because you never explained what you are trying to accomplish. If you are asking in general how to use Expression.ArrayIndex then this is not an NRules question and you should take it to stack overflow or some other Q&A forum.
I'm also asking that issues are used for bug reports and feature requests, and questions are asked on the google forum, stack overflow or gitter channel. See links on the readme page.

**Comment by RockStar201** [comment]
OK check this URL https://stackoverflow.com/questions/57722215
