### ISSUE TITLE
HowTo: Dynamic number of Filter.OnChange expressions

### ISSUE THREAD

**Issue by Smurf-IV** [NRules/NRules#203]
I have a situation where I am matching a variable number of values before a rule can run it's 'update'.

What I want is a way to pass this variable number of values into a the `Filter.OnChange` call?

This is what I have

```C#
            plateModule plate = null;
            IEnumerable<DoubleVariable> values = null;

            When()
                .Match<plateModule>(() => plate)    // Find the owner
                .Query(() => values, x => x
                    .Match<DoubleVariable>(              // Start a list of vars
                        dv => dv.OwnerPart == plate,   // check that this belongs to the owner
                        dv => dv.ValueSet                      // check that it has a value set
                        )
                    .Collect()                                         // aggregate the list
                    .Where(c => c.Count() == plate.DoubleVariables.Count)  // check that all have been accounted for
                );
```
and then want to place the values into the `Filter.OnChange(....` with monitoring the `DoubleVariable.Value` field.
e.g. is this valid ?
```C#
                plate.DoubleVariables.ForEach(dv => Filter()
                    .OnChange(() => dv.Value)
                );
```
Or is there an *Actual* way ?
Especially as the `plate.` **will** be null

**Comment by snikolayev** [comment]
No, that approach won't work. You cannot use fact variables outside DSL expressions.
You basically need to collapse your IEnumerable<DoubleVariable> to an immutable value that can be compared in the OnChange clause.
The most straightforward way would be something like:
```c#
Filter()
    .OnChange(() => string.join("|", plate.DoubleVariables));
```
Or you can wrap it in some custom object that implements IEquatable.
Whatever it is, you can also wrap this in an extension method, so that it looks nicer:
```c#
Filter()
    .OnChange(() => plate.DoubleVariables.GetChangeKey());
```

**Comment by Smurf-IV** [comment]
Thanks for the reply...

> No, that approach won't work. You cannot use fact variables outside DSL expressions.

Agreed, hence `plate` being null.

> You basically need to collapse your IEnumerable to an immutable value that can be compared in the OnChange clause.

Not sure I follow, you mean a single `string` made up of the actual `double` values ?

> Or you can wrap it in some custom object that implements IEquatable.

How does `IEquatable` work over an `IEnumerable` mode up of function pointers to value `get` accessors ? or have I missed something here ?

> Whatever it is, you can also wrap this in an extension method, so that it looks nicer:
> 
> ```cs
> Filter()
>     .OnChange(() => plate.DoubleVariables.GetChangeKey());
> ```

Again; A single value ?
What I want, is for the *individual* values - from the `DoubleVariable IEnumerable` (It's actually a `List<>`) - to be put into the filter watch; because they *may* be modified by other Rules, or Update() calls.


If the `Filter().OnChange(....)` is just calling a function each time to see if a value has changed, then would it not be more efficient if the compare is done on each "individual native" type rather than having to convert it into a massive string each time.

Something like:
```cs
Filter()
    .CreateOnChanges(plate.DoubleVariables.Select(dv => dv.Value));
```
would be great.

**Comment by snikolayev** [comment]
OnChange accepts one or more keys to monitor for changes. But the number of keys must be known at rule compile time. Since you have an unbound collection, you need to flatten it to a single key to pass it to the OnChange filter. I showed you flattening into a string as a naive example of flattening a collection to a single immutable value.
It's also not that bad from performance perspective, since this string (or whatever flattened value you produce) will only be generated when the filter condition is evaluated, which is when the rule already produced a full match.
Imagine what would the engine need to do to support OnChange for collections. It would need to compare two snapshots of that collection, element by element, to determine if anything changed. That is exactly what you can do by implementing a ChangeKey class that wraps your collection and implements IEquatable. That's also in spirit similar to what you were proposing with the CreateOnChanges snippet.
```c#
public class ChangeKey : IEquatable<ChangeKey>
{
    private readonly double[] _items;

    public ChangeKey(IEnumerable<DoubleVariable> items)
    {
        //must snapshot, as the change key must be immutable
        _items = items.Select(x => x.Value).ToArray();
    }

    public bool Equals(ChangeKey other)
    {
        //implement element-wise comparison
    }
}
```

And then in the filter:
```c#
Filter()
    .OnChange(() => new ChangeKey(plate.DoubleVariables));
```

And as before, you can wrap this in an extension method to read better.

**Comment by Smurf-IV** [comment]
In the Equals I put `return false`, and the code **still works** as before (i.e. the DO steps are still run.)
**_It shouldn't !_** A breakpoint on the `false` is never hit either.
Here are the snippets:
```cs
            Filter()
                .OnChange(() => new VariablesExt.ChangeKey(calc.Variables));
            Then()
                .Do(ctx => PerformCalculation(ctx, calc));
```

with the `VariablesExt.ChangeKey` declared as:
```cs
        public class ChangeKey : IEquatable<ChangeKey>
        {
            private readonly object[] items;

            public ChangeKey(IEnumerable<IVariable> items)
            {
                //must snapshot, as the change key must be immutable
                this.items = items.Select( v => v.Value).ToArray();
            }

            public bool Equals(ChangeKey other)
            {
                return false;
                //implement element-wise comparison
                //return other != null && items.SequenceEqual(other.items);
            }
        }
```

**Comment by snikolayev** [comment]
Two things. First, if you return `false` from `Equals` method, it means the keys are not equal, which means the keys DID change, so the `OnChange` filter will pass the value and it is correct that the rule fires.
And second, your implementation of `IEquatable` is incorrect (see https://blogs.msdn.microsoft.com/jaredpar/2009/01/15/if-you-implement-iequatablet-you-still-must-override-objects-equals-and-gethashcode/). In short, you still must override `Object.Equals` and `Object.GetHashCode`. This is why your `Equals` method is not getting hit. It's best to use something like ReSharper for generating equality methods.
For example:
```c#
public class ChangeKey : IEquatable<ChangeKey>
{
    private readonly object[] _items;

    public ChangeKey(IEnumerable<IVariable> items)
    {
        //must snapshot, as the change key must be immutable
        this._items = items.Select( v => v.Value).ToArray();
    }

    public bool Equals(ChangeKey other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return _items.SequenceEqual(other._items);
    }

    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((ChangeKey) obj);
    }

    public override int GetHashCode()
    {
        return _items.GetHashCode();
    }
}
```

**Comment by Smurf-IV** [comment]
Apologies if you feel this is dragging on, but I must be missing something in the implementation somewhere....

>Two things. First, if you return false from Equals method, it means the keys are not equal, which means the keys DID change, so the OnChange filter will pass the value and it is correct that the rule fires.

If I use `return true`, the `Do` **still** fires, I was just simplifying for debug and breakpoints.
 
> And second, your implementation of IEquatable is incorrect

I do use ReSharper, it was very quiet about the `IEquatable`, even with you changes the breakpoints are still not hit, and the `Do` are still fired regardless. (The constructor is called, but the no other method!)
- I am using a single session
- I am using 2 variables for 2 instances of a rule (1 variable each rule)
- Set initial variable before first `Fire`, (I see 1 `ChangeKey` constructor created)
- Call `Fire` and observe that 1 `Do` has been called
- Set 2nd variable, update, (I see 1 `ChangeKey` constructor created)
- Then fire (This is when I would expect the 1st rule to check for equality) and observe that 1 `Do` has been called
- Check that the rule has fired


Here is the Test code:
```cs
 [Fact]
        public void A011_TestInsertTwice()
        {
            //Create a working session
            ISession session = factory.CreateSession();

            //Load domain model
            TestModuleBool apple1 = new TestModuleBool();
            TestModuleBool apple2 = new TestModuleBool();

            //Insert facts into rules engine's memory
            session.Insert(apple1);
            apple1.DoubleVariables.First().SetValue(1);
            session.InsertAll(apple1.DoubleVariables);
            session.Insert(apple2);
            session.InsertAll(apple2.DoubleVariables);

            session.Fire();

            // Assert that the rule has been applied
            Assert.True(apple1.OutputVariable);
            Assert.False(apple2.OutputVariable);

            //// Assert that the rule has been applied
            Assert.False(apple2.OutputVariable.ValueSet);

            apple2.DoubleVariables.First().SetValue(1);
            session.UpdateAll(apple2.Variables);
            session.Fire();

            // Assert that the rule has been applied
            Assert.True(apple1.OutputVariable);
            Assert.True(apple2.OutputVariable);
        }
```

And the rule:
```cs
 public override void Define()
        {
            Calculation calc = null;
            IEnumerable<IVariable> iValues = null;

            When()
                .Match<Calculation>(() => calc)             // Find the owner
                .Query(() => iValues, x => x
                        .Match<IVariable>(                 // Start a list of vars
                            iv => iv.OwnerPart == calc         // check that this belongs to the owner
                                && iv.ValueSet                 // check that it has a value set
                        )
                        .Collect()                              // aggregate the list
                        .Where(c => c.Count() == calc.Variables.Count())  // check that all have been accounted for
                    )
                ;

            // from https://github.com/NRules/NRules/issues/203
            Filter()
                .OnChange(() => new VariablesExt.ChangeKey(calc.Variables));

            Then()
                .Do(ctx => PerformCalculation(ctx, calc));
        }

        public void PerformCalculation(IContext ctx, Calculation calc)
        {
                calc.PerformCalculation();
         }
```

**Comment by snikolayev** [comment]
No worries, we'll get to the bottom of it.

I can't run this test, because it doesn't contain definitions of any of the fact types. Can you create a self-contained test that I can run and observe the behavior you are describing?

Just by looking at it - a few points:
* OnChange filter is expected to only apply when the rule has fired before, during the subsequent fact updates. First time the rule is activated, there is nothing to compare to for the OnChange filter, so the equality of the keys is not checked. I believe you know this, but I want to call it out, because it's important.
* The change key is associated with the rule activation (full rule match), so it only exists as long as all conditions for the match hold true. If at any point any of the conditions are invalidated, the activation is destroyed. Next time the rule matches it is a new activation, with a new match key, so the equality is again not checked. To debug whether activations are updated or deleted and re-created, you can use [Session.Events.ActivationCreated](http://nrules.net/api/html/E_NRules_Diagnostics_IEventProvider_ActivationCreatedEvent.htm), [Session.Events.ActivationDeleted](http://nrules.net/api/html/E_NRules_Diagnostics_IEventProvider_ActivationDeletedEvent.htm), [Session.Events.ActivationUpdated](http://nrules.net/api/html/E_NRules_Diagnostics_IEventProvider_ActivationUpdatedEvent.htm) events.
* The key is supposed to be immutable. I see that you are mutating your variables via SetValue. If you are just snapshoting the references to mutable objects inside the ChangeKey, the filter won't work. Need to make sure to snapshot the immutable values.

**Comment by Smurf-IV** [comment]
The line of interest is in `TestVariables: 54`

[TestNRules.zip](https://github.com/NRules/NRules/files/3749582/TestNRules.zip)

**Comment by snikolayev** [comment]
There are few things.
First (and it's unrelated to filters, but helpful to clarify) - you are loading the rule twice:
```c#
repository.Load(x => x.From(Assembly.GetExecutingAssembly()));
repository.Load(x => x.From(typeof(RavenRule)));
```
First line loads all rules in the assembly, and the second line loads the specific rule again. Remove one of those lines.

Now to the actual filter. You have two instances of TestModuleBool, that you called apple1 and apple2, and you insert both into the session (along with the variables defined in them). But only the first one has the value set. So, this creates one activation, and generates a change key for it.
The second TestModuleBool does not create an activation, because of your match conditions:
```c#
.Match<IVariable>(iv => iv.OwnerPart == calc && iv.ValueSet)
```
It's important to remember that each match creates its own activation, and the filter is applied at the activation level.
Then you are updating apple2 and setting the value, which creates the second activation (and generates a change key for it). 

If you want to see the change key in action, update one of the facts with an existing activation. For example:
```c#
apple2.DoubleVariables.First().SetValue(1);
session.UpdateAll(apple2.Variables);
session.Fire();     //This one creates a new activation, because of SetValue above, so the rule fires

session.UpdateAll(apple2.Variables);
session.Fire();     //This one updates the existing activation, but nothing changed, so the rule doesn't fire
```

**Comment by Smurf-IV** [comment]
Thanks for taking time out for this....

> There are few things.
> First (and it's unrelated to filters, but helpful to clarify) - you are loading the rule twice:
> ```cs
> repository.Load(x => x.From(Assembly.GetExecutingAssembly()));
> repository.Load(x => x.From(typeof(RavenRule)));
> ```

That was a "copy and paste" and forgetting to "tidy up" error !

> Now to the actual filter. You have two instances of TestModuleBool, that you called apple1 and apple2, and you insert both into the session (along with the variables defined in them). But only the first one has the value set. So, this creates one activation, and generates a change key for it.

That is correct, to try an emulate "Late updates" of multiple variables later on.

> The second TestModuleBool does not create an activation, because of your match conditions:
> ```cs
> .Match<IVariable>(iv => iv.OwnerPart == calc && iv.ValueSet)
> ```

Agreed.

> It's important to remember that each match creates its own activation, and the filter is applied at the activation level.
> Then you are updating apple2 and setting the value, which creates the second activation (and generates a change key for it).

OK.

> If you want to see the change key in action, update one of the facts with an existing activation. For example:
> 
> ```cs
> apple2.DoubleVariables.First().SetValue(1);
> session.UpdateAll(apple2.Variables);
> session.Fire();     //This one creates a new activation, because of SetValue above, so the rule fires
> ```

And I put this before the next part:
`apple2.DoubleVariables.First().SetValue(2);`
> ```cs
> session.UpdateAll(apple2.Variables);
> session.Fire();     //This one updates the existing activation, but nothing changed, so the rule doesn't fire
> ```

And Now I see the Equality being fired. 
Now I understand why I was not seeing the firing, because internally (I am assuming) in the NRules compiler, it is being "Very" efficient in the way it needs to call the filters, and hence the need to not calling the Do functionality if it has only been evaluated once..

Again thanks for going through this with me.
