### ISSUE TITLE
Dynamic rule loading

### ISSUE THREAD

**Issue by FauzaanHafeez** [NRules/NRules#206]
Hi, 

I want to write loosely coupled code, where I can add/remove rules during runtime. How can I load rules during runtime (like reading from a file or DB)? And how can I enable/disable any rule in the production environment during runtime without having to recompile the application?

**Comment by snikolayev** [comment]
You can create rules at run time using the `RuleBuilder` (see https://github.com/NRules/NRules/wiki/Rule-Builder). Alternatively, you can distribute rules as plugins and load them dynamically (e.g. using MEF). In case of using MEF you would still need to compile rules, but you don't need to recompile the application.
If you want to store rules in the DB, etc., then RuleBuilder is the only option.
You may also be interested in https://github.com/NRules/NRules.Language

**Comment by FauzaanHafeez** [comment]
> You can create rules at run time using the `RuleBuilder` (see https://github.com/NRules/NRules/wiki/Rule-Builder). Alternatively, you can distribute rules as plugins and load them dynamically (e.g. using MEF). In case of using MEF you would still need to compile rules, but you don't need to recompile the application.
> If you want to store rules in the DB, etc., then RuleBuilder is the only option.
> You may also be interested in https://github.com/NRules/NRules.Language

Can I somehow write the rule in the form of a string and then compile it at runtime? Please give a code sample if possible? 
Also, can you please provide a code sample for the MEF technique that you mentioned. I am trying to use nrules with my .net web application where I'll need to dynamically add/remove/modify rules without having to stop the server.

I'll be thankful for the help

**Comment by DanielMPries** [comment]
I've done this a few times.  At app startup, you can read the information you need and generate code, build that code, and dynamically attach the assembly.  There will need to be a bit of strategy involved to let your IoC container know of the dependency wire-up if you're using that.  [Here's a tutorial on how to do dynamic classlib generation.](https://keestalkstech.com/2016/05/how-to-add-dynamic-compilation-to-your-projects/).  

In an enterprise environment this opens some possibilities that could put your application and organization at risk So you may want each runtime build code and binary stored somewhere at each dynamic compilation so that it can be audited if need be.  With great power comes great responsibility.

**Comment by snikolayev** [comment]
Thank you @DanielMPries for good info
