### ISSUE TITLE
NRule working memory size

### ISSUE THREAD

**Issue by AnandPalanidurai** [NRules/NRules#253]
Is there any limitations in NRules working memory size. What is max limit of NRules working memory? @snikolayev Please help on this

**Comment by snikolayev** [comment]
What’s the scenario you are thinking about?

Also, if possible, in the future please ask questions on gitter or stack overflow.

**Comment by PalaniduraiAnand** [comment]
@snikolayev  Thank you for the response . We are planning to use NRules for our new project which has lot of business rules for each session. I would like to use dynamic rule builder to map the rules which is coming from DB. Since we have so many business rules (approx. more than 1000) and facts (approx. more than 100)  for each session I would like to know will there be any limitations on Rules and facts for a single session ? What is the max amount of rules and facts that  can be loaded into NRules engine memory for a single session.  Also noted will raise questions in gitter or stack overflow in future.  Thank you.

**Comment by snikolayev** [comment]
There is no hard limit in NRules on the number of rules or the number of facts. But performance and the memory footprint scale with the number and complexity of conditions in the rules. Of course there is node sharing (same conditions in different rules may be shared at run time). So, you'll have to experiment and see if your rules and your facts will result in acceptable performance (and memory footprint).

**Comment by PalaniduraiAnand** [comment]
Understand. Sure, We will explore further . Thank you so much @snikolayev
