### ISSUE TITLE
.Having() clause disregards variable name, operates on most recent variable instead

### ISSUE THREAD

**Issue by marked23** [NRules/NRules#279]
I'm not sure if I'm misusing the .Having() clause.  I noticed this unexpected behavior. 

When I have matched-in two objects of the same type, then add a Having() clause:  The Having() clause will operate on the values of the most-recently matched object... not the object bound to that variable name. 

In the example below, both conditions in the Having clause operate against the "outbound" variable.

If I swap the order of the Matches, so that inbound is the most recent Match, the Having clause operates on the "inbound" variable. 

I solved my problem by moving those conditions into the Matches.  Which is probably the better choice anyway.  But I thought you would like to know about this unexpected behavior. 

```csharp
public override void Define()
{
    Flight flight = default;
    Record outbound = default;
    Record inbound = default;

    When()
        .Match(() => flight)
        .Match(() => inbound,  i => i.Id == flight.Id,
                               i => i.RecordType.ToLower() == "inbound")
        .Match(() => outbound, o => o.Id == flight.Id,
                               o => o.RecordType.ToLower() == "outbound")
        .Having(
            () => !outbound.Name.Equals(inbound.Name),
            // The value of outbound.Name is sent to WordCount(), instead of inbound.Name
            () => inbound.Name.WordCount() > 2
        );

    Then()
        .Do(ctx => flight.AddAnomaly("Some message")
        .Do(ctx => ctx.Update(flight));
}
```

**Comment by snikolayev** [comment]
Thank you @marked23 for reporting this and for a repro scenario. I'll take a look. In the meantime, can you please confirm the version of the NRules that you are using?

**Comment by marked23** [comment]
I'm using v0.9.2

**Comment by snikolayev** [comment]
The `Having` clause is always attached to the pattern that immediately precedes it. In this case it was attached to the outbound fact pattern. But it had a single-argument condition for the inbound fact. This is all fine, but this condition would need to be checked in the beta network (in the join node), such that it has access to both facts. But since the condition only had a single argument it was classified as an alpha condition and thus pushed into the alpha network, getting attached to the wrong node.
