### ISSUE TITLE
Visualizer uses deprecated BinaryFormatter

### ISSUE THREAD

**Issue by Entropy0** [NRules/NRules#296]
Trying to use the nifty Visualizer feature for an ASMP.NET Core 5.0 project will fail with a message saying "BinaryFormatter is not supported on the debuggee-side".

That is because BinaryFormatter has been [deprecated and automatically disabled](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete) for newer projects due to security concerns. The recommended action is to use [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) or [XmlSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer) instead.

---

As a workaround for those who want to use this Visualizer for their core 5.0 projects in the meantime:
You _can_ enable BinaryFormatter again for your project by setting `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` in your project's .csproj file, but beware that [it is explicitly recommended **not** to do this](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)!

**Comment by snikolayev** [comment]
It turns out that the underlying infrastructure in VS libraries that supports debugger visualizer uses the BinaryFormatterSerialization under the hood by default. Described here: https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.visualizer.troubleshoot)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=vs-2022#special-debugger-side-considerations-for-net-50

But given that we transfer data between debuggee and debugger as an XML string (which is the rete graph in the DGML format), we can just write/read the raw string to the stream and bypass default serialization used by the debugger visualizer base classes.
