### ISSUE TITLE
Add .NET 6 target on top of .NET Standard 2.x

### ISSUE THREAD

**Issue by gritcsenko** [NRules/NRules#316]
Currently all packages targeting .NET Standard 2.x.
.NET 6 adds new APIs that can be used in NRules to reduce amount of code and improve performance.

**Comment by snikolayev** [comment]
@gritcsenko can you please elaborate on what you have in mind? NRules must continue targeting .net standard 2.x, so if .net 6 target is in addition, can you really reduce amount of code? You can use .net 6 specific features to improve performance, but you'd have to if/def around it and provide a fallback implementation for .net standard. This will of course benefit the performance of .net 6 clients, but at the expense of more code and higher complexity.
Please let me know if I'm missing something

**Comment by douglasg14b** [comment]
Thinking about this. This library could just target the newest .Net version for not-insignificant performance & allocation improvements without much involvement?

It doesn't have to use new syntax or constructs, which is where the pain comes in with all the compiler conditions.

Just speculating

**Comment by gritcsenko** [comment]
I was thinking about using .NET 6 API to gain performance boost and reduce memory consumption. 
Also, I've spotted a lot of unnecessary collection allocations that can be avoided by utilizing .NET 6 API.

**Comment by snikolayev** [comment]
At least for some time, I think it's beneficial to target .net standard, so that this library is available under .net framework. When used form an application that targets .net 6 runtime, it gets all the benefits. So, @douglasg14b, if you really mean just get the benefits of the runtime, w/o using new APIs, then you are getting that from just using NRules from within a .net 6 app.
To gain more improvements, as @gritcsenko said, we would need to start using new .net 6 APIs and constructs. I'm happy to do that for some localized changes in high-traffic high-impact areas with conditional compilation, if there is a commensurate improvement for this additional complexity. But I don't want to fork and duplicate the whole project or completely forfeit .net framework.
Do you have any specific code areas in mind?

**Comment by douglasg14b** [comment]
Ah gotcha, I guess I didn't think about it enough. If the runtime version is where the benefits are afforded (And now that you mention it, I think you're right, it's not like your package has the runtime bundled with it or anything >_>). Then it might be pretty painful to adopt use of new APIs without a clear & demonstrable benefit first.
