### ISSUE TITLE
IEquatable object fails with error?

### ISSUE THREAD

**Issue by asulwer** [NRules/NRules#361]
if object inherits from IEquatable then rules fail with error?

![image](https://github.com/user-attachments/assets/18191511-8724-4d4d-932b-65d03df802da)

```
public class Card : IEquatable<Card>
{
    public string Name { get; set; } = string.Empty;
    public string Site { get; set; } = string.Empty;
    public string Extra { get; set; } = string.Empty;

    public bool Equals(Card? c) => Name == c?.Name;
    public override bool Equals(object? obj) => Equals(obj as Card);
    public override int GetHashCode() => (Name).GetHashCode();
}
```

```
public class TestRule : Rule
{
    public override void Define()
    {
        Card card = default!;

        When()
            .Match(() => card, c => c.Name.Contains(" - FOIL"));

        Then()
            .Do(ctx => ctx.Update(card, ChangeName));
    }

    private static void ChangeName(Card card)
    {
        card.Name = card.Name.Replace(" - FOIL",string.Empty);
    }
}
```

```
var cards = new List<Card>
{
    new Card { Name = "Fart - FOIL", Site = "Abu" }
};

var repository = new RuleRepository();
repository.Load(x => x.From(typeof(TestRule)));

var factory = repository.Compile();
var session = factory.CreateSession();

session.InsertAll(cards);
session.Fire();
```

**Comment by snikolayev** [comment]
@asulwer it's failing not because the fact implements `IEquatable`, but because the identity of the fact is getting mutated. Fact's equality is used to lookup the internal fact data structure, based on the passed fact object. Since you are calling an "Update" you are basically saying that the fact already exists, but of course it cannot be found, because you just changed the field which is part of fact's identity.
In essence, facts with structural equality must be immutable - it's the current limitation. Currently equality comparison is used for fact's identity,
As a solution, you can define an Id property and use that for equality comparison.
You can also see #336 for details of the behavior and the proposed enhancement.

**Comment by asulwer** [comment]
@snikolayev thank you very much for the detailed answer.  using an Id field instead of the Name worked.  i overlooked the fact that in production i will not be solely using the Name field.
