### ISSUE TITLE
Rule Design

### ISSUE THREAD

**Issue by drusellers** [NRules/NRules#60]
Ok, I'm probably doing something dumb. But my guess is that NRule should probably not run forever and should detect a cycle.

https://gist.github.com/drusellers/d61cf0d9ecfe382b5fb8

When I run these rules, what I'm hoping to get is that it sees the order is for $100 and fires a discount per the rule. It could se that the order is for 100 and over and applies free shipping. But then when the discount is applied it should revoke free shipping if that has already been applied as well.

With the debugger on, I see it going back and forth from rule 3 to rule 2. Is this expected behavior? I feel like I need the repeatability on, since I don't know which rule will fire first.

**Comment by snikolayev** [comment]
Hi Dru, I only have access to a cell phone right now, so I can't run the example, but here is some info,  until I get to the computer on Monday. 
When you call Update on a fact, it reevaluates all rules that match on that fact. Every rule that matches will get activated, even if it fired before, as long as its conditions are still true. Unless the rule is non repeatable. There  is no magic in the engine (yet :-) ) to break the loops.
There are several strategies to prevent loops. 
* Make sure conditions are no longer true after the rule fires. I.e. only apply discount if it hasn't been applied yet. 
* Use additive reasoning. I.e. add new facts instead of modifying existing ones (i.e. insert a Discount fact)
* Juggle rule priorities and non repeatability to get the desired effect. 

There are probably some more advanced recursion controls that the engine can implement, so I'll look at that too.

**Comment by drusellers** [comment]
@snikolayev thank you for taking the time to answer via cell phone (the torture) - I _thought_ i had it so the rules should no longer be true. So I'll have to double check that. Thank you, also, I'd love to hear / see more about best practices in building rules. I'm happy to be the guy who asks you a million questions to extract these out of your brain. :)

**Comment by snikolayev** [comment]
@drusellers, absolutely, I don't mind the questons at all! If you extract anything useful, we can also turn it into a wiki page :)

**Comment by snikolayev** [comment]
@drusellers 
Check out this updated example. I modified the rules, so that they don't go into an infinite loop anymore. I also added some additional diags, so that you can see what's going on.
https://gist.github.com/snikolayev/6eff1a32eacf3a5a8591

**Comment by snikolayev** [comment]
@drusellers I updated the gist with some more diags, to clarify how engine works. Let me know if this helps.
https://gist.github.com/snikolayev/6eff1a32eacf3a5a8591
