### ISSUE TITLE
Ability to resolve multiple instances of the same Rule Type with different config

### ISSUE THREAD

**Issue by jcfarsight** [NRules/NRules#65]
I've got a quick question about resolving dependencies or activating rules at run-time. In a potential project I'm working on we have a number of rules that check the same criteria for different values and then action different treatments.

I currently have a custom RuleActivator implementing the IRuleActivator interface, but the Activate method only takes a Type which is fine in circumstances where there is one rule instance per Type. It doesn't allow multiple instances of the same Type however.

Here's a quick example I threw together to demonstrate my situation:

    public class DebtStageTenureRule : Rule
    {
      private DebtStage debtStage;

      private int minimumAccountTenure;

      private Treatment treatment;

      public DebtStageTenureRule(DebtStage debtStage, int minimumAccountTenure, Treatment treatment)
      {
         this.debtStage = debtStage;
         this.minimumAccountTenure = minimumAccountTenure;
         this.treatment = treatment;
      }

      public override void Define()
      {
         Consumer consumer = null;

         When()
            .Match<Consumer>(() => consumer, c => c.DebtStage.Equals(debtStage))
            .Match<Consumer>(c => c.Tenure >= minimumAccountTenure);

         Then()
            .Do(context => consumer.ApplyTreatment(treatment));
      }
    }

Now let's say I want to configure two rules of this Type using Spring Framework IoC.
1) Debt stage of A and MinimumTenure of 300 gives a treatment of TreatmentX.
2) Debt stage of B and MinimumTenure of 500 gives a treatment of TreatmentY.

Would it possible to do this without making DebtStageTenureRule an abstract class and creating two inheriting classes just for the different Types?

I noticed the Name attribute you can place on a Rule but I presume this is just metadata for logging and/or event handler context.

**Comment by snikolayev** [comment]
@jcfarsight - this is an interesting approach. I always thought of a rule type to be 1:1 with the rule definition, but what you are trying to do makes a lot of sense.
So, I imagine `IRuleActivator.Activate` needs to return a collection of instances, instead of just a single instance. Plus, you need a way to override a rule name (yes, rule name is just a piece of metadata, but it seems useful to have ability to define unique names for different instances).

The rule may look something like this:
```c#
  public override void Define()
  {
      Name(string.Format("Debt stage of {0} Rule", debtStage));
      //..
  }
```
I'll experiment a bit to make sure it does not break some other assumptions, but I think I should be able to support this in the next release.

**Comment by jcfarsight** [comment]
This sounds good to me. Thanks.
