### ISSUE TITLE
Dynamic rule priority via expression

### ISSUE THREAD

**Issue by snikolayev** [NRules/NRules#75]

**Comment by snikolayev** [comment]
Unmerged from develop branch and moved into feature-priority. Need to give this more thought how to properly do it.

**Comment by DanielMPries** [comment]
So I think if there were some sort of DependsOn decorator (attribute) or derived type of Rule that exposed that that information, the chain could be derived and the rules could be topologically organized.  I guess the problem is, it would be all or nothing and your soft of back to the priority approach

**Comment by snikolayev** [comment]
This looks like a material piece complexity, w/o a clear need. So, won’t fix
